In [1]:
import numpy as np
import pandas as pd

from sklearn import datasets

In [2]:
pd.options.mode.chained_assignment = None

np.random.seed(1)

In [3]:
CLUSTERS_COUNT = 3

iris = datasets.load_iris()
data = iris.data
target = iris.target
target_names = iris.target_names

preprocessed_data = data.copy()

print(pd.read_csv('./data/iris.data'))

DIMENSIONAL = data.shape[1]
SIZE = data.shape[0]

As = np.array([np.identity(DIMENSIONAL), np.identity(DIMENSIONAL), np.identity(DIMENSIONAL)])

EPSILON = 0.000005

     5.1  3.5  1.4  0.2     Iris-setosa
0    4.9  3.0  1.4  0.2     Iris-setosa
1    4.7  3.2  1.3  0.2     Iris-setosa
2    4.6  3.1  1.5  0.2     Iris-setosa
3    5.0  3.6  1.4  0.2     Iris-setosa
4    5.4  3.9  1.7  0.4     Iris-setosa
..   ...  ...  ...  ...             ...
144  6.7  3.0  5.2  2.3  Iris-virginica
145  6.3  2.5  5.0  1.9  Iris-virginica
146  6.5  3.0  5.2  2.0  Iris-virginica
147  6.2  3.4  5.4  2.3  Iris-virginica
148  5.9  3.0  5.1  1.8  Iris-virginica

[149 rows x 5 columns]


In [4]:
def encode_on_hypercube(data):
    """
    Метод для кодирования на гиперкуб
    
    :param data: DataFrame instance
    return DataFrame instance
    """
    def encode_by_column(column):
        minimum, maximum = np.min(column), np.max(column)
        return np.apply_along_axis(lambda x: 2 * (x - minimum) / (maximum - minimum) - 1, 0, column)
    
    return np.apply_along_axis(encode_by_column, 0, data)

In [5]:
preprocessed_data = encode_on_hypercube(preprocessed_data)
np.random.shuffle(preprocessed_data)

cluster_column = np.zeros((data.shape[0], 1))
preprocessed_data = np.append(preprocessed_data, cluster_column, axis=1)
preprocessed_data

array([[-1.66666667e-01,  6.66666667e-01, -9.32203390e-01,
        -9.16666667e-01,  0.00000000e+00],
       [-5.55555556e-01, -5.83333333e-01, -3.22033898e-01,
        -1.66666667e-01,  0.00000000e+00],
       [ 2.77777778e-01, -1.66666667e-01,  1.52542373e-01,
         8.33333333e-02,  0.00000000e+00],
       [-3.88888889e-01,  5.83333333e-01, -8.98305085e-01,
        -7.50000000e-01,  0.00000000e+00],
       [ 1.00000000e+00,  5.00000000e-01,  8.30508475e-01,
         5.83333333e-01,  0.00000000e+00],
       [ 1.11111111e-01,  8.33333333e-02,  2.54237288e-01,
         2.50000000e-01,  0.00000000e+00],
       [ 4.44444444e-01, -8.33333333e-02,  3.89830508e-01,
         8.33333333e-01,  0.00000000e+00],
       [-5.55555556e-01,  5.00000000e-01, -6.94915254e-01,
        -7.50000000e-01,  0.00000000e+00],
       [-7.77777778e-01,  0.00000000e+00, -7.96610169e-01,
        -9.16666667e-01,  0.00000000e+00],
       [ 4.44444444e-01,  0.00000000e+00,  5.93220339e-01,
         8.33333333e-01

In [6]:
centroids = np.random.uniform(low=-1, high=1, size=(CLUSTERS_COUNT, DIMENSIONAL))
centroids

array([[ 0.24672023, -0.96835751,  0.85887447,  0.38179384],
       [ 0.9946457 , -0.65531898, -0.7257285 ,  0.86519093],
       [ 0.39363632, -0.86799965,  0.51092611,  0.50775238]])

In [7]:
def get_distance(row, center, A):
    diff = row - center
    result = np.dot(np.dot(diff.reshape((1, DIMENSIONAL)), A), diff.reshape((DIMENSIONAL, 1)) ).item()

    return result

In [8]:
def get_owners(data, centers, As):
    owners = np.zeros((SIZE, CLUSTERS_COUNT))
    for index, row in enumerate(data):
        distances = np.array([1 / get_distance(row[:DIMENSIONAL], center, np.linalg.inv(As[n_index])) 
                              for n_index, center in enumerate(centers)])
        sum_distances = np.sum(distances)

        owners[index] = np.array([
            dist / sum_distances for dist in distances
        ])
    
    assert owners.shape == (SIZE, CLUSTERS_COUNT)

    return owners

In [9]:
def get_centroids(data, owners):
    sqrt_owners = np.power(owners, 2)
    
    sum_center = np.apply_along_axis(np.sum, 0, sqrt_owners)
    
    sum_data = np.zeros((CLUSTERS_COUNT, DIMENSIONAL))
    for index, row in enumerate(data):
        sum_data += np.dot(
            sqrt_owners[index].reshape((CLUSTERS_COUNT, 1)),
            row[:DIMENSIONAL].reshape((1, DIMENSIONAL))
        )
    
    result = sum_data / sum_center.reshape((CLUSTERS_COUNT, 1))

    assert result.shape == (CLUSTERS_COUNT, DIMENSIONAL)
    return result

In [10]:
def get_new_Fs(data, centroids, owners):
    Fs = np.zeros((CLUSTERS_COUNT, DIMENSIONAL, DIMENSIONAL))
    
    sqrt_owners = np.power(owners, 2)
    
    for index, center in enumerate(centroids):

        for n_index, row in enumerate(data):
            diff = row[:DIMENSIONAL] - center   

            Fs[index] += np.dot(
                (sqrt_owners[n_index][index] * diff).reshape((DIMENSIONAL, 1)),
                diff.reshape((1, DIMENSIONAL))
            )
        Fs[index] /= np.sum(sqrt_owners.T[index])

    return Fs

In [11]:
def get_new_As(data, centroids, owners):
    Fs = get_new_Fs(data, centroids, owners)
    
    As = np.zeros((CLUSTERS_COUNT, DIMENSIONAL, DIMENSIONAL))
    for index, F in enumerate(Fs):
        As[index] = np.sqrt(np.sqrt(1 / np.linalg.det(F))) * F
    
    return As

In [12]:
def get_answer(data, centroids, As):
    owners = get_owners(data, centroids, As)
    new_centroids = get_centroids(data, owners)
    
    As = get_new_As(data, new_centroids, owners)
        
    while any([get_distance(new_centroids[index], centroids[index], As[index]) > EPSILON
               for index in range(centroids.shape[0])
              ]):
        owners = get_owners(data, new_centroids, As)

        centroids = new_centroids
        new_centroids = get_centroids(data, owners)
        As = get_new_As(data, new_centroids, owners)

    return data, new_centroids, As, owners

In [13]:
result_data, new_centroids, new_As, new_owners = get_answer(preprocessed_data, centroids, As)

In [14]:
new_centroids

array([[ 0.02022624, -0.33183622,  0.19428502,  0.08806911],
       [-0.60319312,  0.1983778 , -0.84222725, -0.87996004],
       [ 0.16188103, -0.18695067,  0.45617274,  0.59356582]])

In [15]:
new_owners

array([[0.0500374 , 0.92810153, 0.02186107],
       [0.69954165, 0.09678189, 0.20367646],
       [0.77253351, 0.02036304, 0.20710345],
       [0.04206705, 0.9413    , 0.01663295],
       [0.64671921, 0.02431087, 0.32896992],
       [0.67892607, 0.01706891, 0.30400501],
       [0.16730175, 0.02989657, 0.80280168],
       [0.06503395, 0.90656461, 0.02840144],
       [0.02639001, 0.9631102 , 0.01049978],
       [0.06312154, 0.00483162, 0.93204684],
       [0.82263903, 0.00949962, 0.16786135],
       [0.02735377, 0.96132642, 0.0113198 ],
       [0.2526591 , 0.00747358, 0.73986732],
       [0.78010545, 0.01555698, 0.20433757],
       [0.80711587, 0.00557004, 0.18731409],
       [0.05056644, 0.93121006, 0.0182235 ],
       [0.92376862, 0.00668821, 0.06954316],
       [0.53217334, 0.0207022 , 0.44712446],
       [0.05288129, 0.92820924, 0.01890947],
       [0.03611688, 0.95136409, 0.01251903],
       [0.55356913, 0.02838862, 0.41804225],
       [0.4702265 , 0.03016096, 0.49961254],
       [0.

In [ ]:
d = {0: 0, 1: 0, 2: 0}
for owner in new_owners:
    d[owner.argmax()] += 1
    
print(d)

{0: 59, 1: 50, 2: 41}
